from __future__ import annotations

KR_RSS_FEEDS = [
    ("보안뉴스", "https://www.boannews.com/media/news_rss.xml"),
    ("데일리시큐", "https://www.dailysecu.com/rss/allArticle.xml"),
    (
        "Google News 랜섬웨어",
        "https://news.google.com/rss/search?q=%EB%9E%9C%EC%84%AC%EC%9B%A8%EC%96%B4+when:1d&hl=ko&gl=KR&ceid=KR:ko",
    ),
    (
        "Google News 정보유출",
        "https://news.google.com/rss/search?q=%EC%A0%95%EB%B3%B4%EC%9C%A0%EC%B6%9C+when:1d&hl=ko&gl=KR&ceid=KR:ko",
    ),
    (
        "Google News 사이버공격",
        "https://news.google.com/rss/search?q=%EC%82%AC%EC%9D%B4%EB%B2%84%EA%B3%B5%EA%B2%A9+when:1d&hl=ko&gl=KR&ceid=KR:ko",
    ),
    (
        "Google News 해킹",
        "https://news.google.com/rss/search?q=%ED%95%B4%ED%82%B9+when:1d&hl=ko&gl=KR&ceid=KR:ko",
    ),
    (
        "Google News APT",
        "https://news.google.com/rss/search?q=APT+%EC%82%AC%EC%9D%B4%EB%B2%84+when:1d&hl=ko&gl=KR&ceid=KR:ko",
    ),
]

GLOBAL_RSS_FEEDS = [
    ("The Hacker News", "https://feeds.feedburner.com/TheHackersNews"),
    ("BleepingComputer", "https://www.bleepingcomputer.com/feed/"),
    ("Dark Reading", "https://www.darkreading.com/rss.xml"),
    ("Krebs on Security", "https://krebsonsecurity.com/feed/"),
    ("SecurityWeek", "https://www.securityweek.com/feed/"),
    ("The Record", "https://therecord.media/feed"),
    ("CyberScoop", "https://cyberscoop.com/feed/"),
    ("CISA Advisories", "https://www.cisa.gov/cybersecurity-advisories/all.xml"),
    ("Microsoft Security", "https://www.microsoft.com/en-us/security/blog/feed/"),
    ("Cisco Talos", "https://blog.talosintelligence.com/rss/"),
    ("Palo Alto Unit 42", "https://unit42.paloaltonetworks.com/feed/"),
    (
        "Google News ransomware",
        "https://news.google.com/rss/search?q=ransomware+attack+when:1d&hl=en-US&gl=US&ceid=US:en",
    ),
    (
        "Google News data breach",
        "https://news.google.com/rss/search?q=data+breach+when:1d&hl=en-US&gl=US&ceid=US:en",
    ),
    (
        "Google News cyber attack",
        "https://news.google.com/rss/search?q=cyber+attack+when:1d&hl=en-US&gl=US&ceid=US:en",
    ),
]

KR_DOMAINS = (
    "boannews.com",
    "dailysecu.com",
    "zdnet.co.kr",
    "etnews.com",
    "it.chosun.com",
    "bloter.net",
    "byline.network",
    "yna.co.kr",
    "yonhapnews.co.kr",
    "newsis.com",
    "news1.kr",
    "donga.com",
    "kisa.or.kr",
    "krcert.or.kr",
    "securityworld.kr",
    "ahnlab.com",
    "estsecurity.com",
)

GLOBAL_DOMAINS = (
    "thehackernews.com",
    "bleepingcomputer.com",
    "darkreading.com",
    "krebsonsecurity.com",
    "securityweek.com",
    "therecord.media",
    "cyberscoop.com",
    "cisa.gov",
    "microsoft.com",
    "talosintelligence.com",
    "paloaltonetworks.com",
    "reuters.com",
    "bbc.co.uk",
    "bbc.com",
    "techcrunch.com",
    "zdnet.com",
    "infosecurity-magazine.com",
    "recordedfuture.com",
    "mandiant.com",
    "crowdstrike.com",
    "sentinelone.com",
    "fortinet.com",
    "cisco.com",
    "nist.gov",
    "ncsc.gov.uk",
    "wsj.com",
    "ft.com",
    "bloomberg.com",
    "theguardian.com",
    "apnews.com",
)

INCIDENT_KEYWORDS = (
    "ransomware",
    "랜섬",
    "breach",
    "유출",
    "leak",
    "hack",
    "해킹",
    "attack",
    "공격",
    "incident",
    "침해",
    "malware",
    "apt",
    "lockbit",
    "blackcat",
    "cl0p",
    "lazarus",
    "ddos",
    "deface",
    "디페이스",
    "phishing",
    "피싱",
    "zero-day",
    "취약점",
    "vulnerability",
    "exploit",
)
